---
- name: "YuvOps - Upgrading packages"
  become: true
  apt:
    upgrade: 'yes'
    state: fixed

- name: "YuvOps - Installing Node & NPM"
  become: true
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: "YuvOps - Installing PM2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "YuvOps - Creating directory"
  file:
    path: ./backend-app
    state: directory
