---
- name: "YuvOps - Updating packages"
  become: yes
  apt:
    update_cache: yes

- name: "YuvOps - Upgrading packages"
  become: yes
  apt:
    upgrade: yes

- name: "YuvOps - Installing Node & NPM"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "YuvOps - Installing PM2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present